export const SET_NUMBER_OF_DICE = 'SET_NUMBER_OF_DICE';
export const SET_NUMBER_OF_FACES = 'SET_NUMBER_FACES';
export const SELECT_COLOR = 'SELECT_COLOR';
export const UPDATE_DICES = 'UPDATE_DICES';
export const UPDATE_RANDOM_DICES = 'UPDATE_RANDOM_DICES';
export const SET_ACTIVE = 'SET_ACTIVE';
